// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: b24llm.proto

package b24llmpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_b24llm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_b24llm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_b24llm_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorDetail   string                 `protobuf:"bytes,2,opt,name=error_detail,json=errorDetail,proto3" json:"error_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_b24llm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_b24llm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_b24llm_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetErrorDetail() string {
	if x != nil {
		return x.ErrorDetail
	}
	return ""
}

type Generation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Temperature   *float32               `protobuf:"fixed32,1,opt,name=temperature,proto3,oneof" json:"temperature,omitempty"`
	MaxTokens     *int32                 `protobuf:"varint,2,opt,name=max_tokens,json=maxTokens,proto3,oneof" json:"max_tokens,omitempty"`
	StopSequences []string               `protobuf:"bytes,3,rep,name=stop_sequences,json=stopSequences,proto3" json:"stop_sequences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation) Reset() {
	*x = Generation{}
	mi := &file_b24llm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation) ProtoMessage() {}

func (x *Generation) ProtoReflect() protoreflect.Message {
	mi := &file_b24llm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation.ProtoReflect.Descriptor instead.
func (*Generation) Descriptor() ([]byte, []int) {
	return file_b24llm_proto_rawDescGZIP(), []int{2}
}

func (x *Generation) GetTemperature() float32 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

func (x *Generation) GetMaxTokens() int32 {
	if x != nil && x.MaxTokens != nil {
		return *x.MaxTokens
	}
	return 0
}

func (x *Generation) GetStopSequences() []string {
	if x != nil {
		return x.StopSequences
	}
	return nil
}

type TaskComment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        string                 `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Time          string                 `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskComment) Reset() {
	*x = TaskComment{}
	mi := &file_b24llm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskComment) ProtoMessage() {}

func (x *TaskComment) ProtoReflect() protoreflect.Message {
	mi := &file_b24llm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskComment.ProtoReflect.Descriptor instead.
func (*TaskComment) Descriptor() ([]byte, []int) {
	return file_b24llm_proto_rawDescGZIP(), []int{3}
}

func (x *TaskComment) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *TaskComment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TaskComment) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type ChecklistItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Done          string                 `protobuf:"bytes,2,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChecklistItem) Reset() {
	*x = ChecklistItem{}
	mi := &file_b24llm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChecklistItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChecklistItem) ProtoMessage() {}

func (x *ChecklistItem) ProtoReflect() protoreflect.Message {
	mi := &file_b24llm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChecklistItem.ProtoReflect.Descriptor instead.
func (*ChecklistItem) Descriptor() ([]byte, []int) {
	return file_b24llm_proto_rawDescGZIP(), []int{4}
}

func (x *ChecklistItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ChecklistItem) GetDone() string {
	if x != nil {
		return x.Done
	}
	return ""
}

type SubtaskWire struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubtaskWire) Reset() {
	*x = SubtaskWire{}
	mi := &file_b24llm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubtaskWire) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtaskWire) ProtoMessage() {}

func (x *SubtaskWire) ProtoReflect() protoreflect.Message {
	mi := &file_b24llm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtaskWire.ProtoReflect.Descriptor instead.
func (*SubtaskWire) Descriptor() ([]byte, []int) {
	return file_b24llm_proto_rawDescGZIP(), []int{5}
}

func (x *SubtaskWire) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubtaskWire) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SubtaskWire) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UserFieldWire struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFieldWire) Reset() {
	*x = UserFieldWire{}
	mi := &file_b24llm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFieldWire) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFieldWire) ProtoMessage() {}

func (x *UserFieldWire) ProtoReflect() protoreflect.Message {
	mi := &file_b24llm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFieldWire.ProtoReflect.Descriptor instead.
func (*UserFieldWire) Descriptor() ([]byte, []int) {
	return file_b24llm_proto_rawDescGZIP(), []int{6}
}

func (x *UserFieldWire) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *UserFieldWire) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type TaskAttachmentWire struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAttachmentWire) Reset() {
	*x = TaskAttachmentWire{}
	mi := &file_b24llm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAttachmentWire) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAttachmentWire) ProtoMessage() {}

func (x *TaskAttachmentWire) ProtoReflect() protoreflect.Message {
	mi := &file_b24llm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAttachmentWire.ProtoReflect.Descriptor instead.
func (*TaskAttachmentWire) Descriptor() ([]byte, []int) {
	return file_b24llm_proto_rawDescGZIP(), []int{7}
}

func (x *TaskAttachmentWire) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskAttachmentWire) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_b24llm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_b24llm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_b24llm_proto_rawDescGZIP(), []int{8}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AnalyzeRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	TaskId                   string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskTitle                string                 `protobuf:"bytes,2,opt,name=task_title,json=taskTitle,proto3" json:"task_title,omitempty"`
	TaskDescription          string                 `protobuf:"bytes,3,opt,name=task_description,json=taskDescription,proto3" json:"task_description,omitempty"`
	TaskStatus               string                 `protobuf:"bytes,4,opt,name=task_status,json=taskStatus,proto3" json:"task_status,omitempty"`
	TaskDeadline             string                 `protobuf:"bytes,5,opt,name=task_deadline,json=taskDeadline,proto3" json:"task_deadline,omitempty"`
	TaskAssignee             string                 `protobuf:"bytes,6,opt,name=task_assignee,json=taskAssignee,proto3" json:"task_assignee,omitempty"`
	TaskPriority             string                 `protobuf:"bytes,7,opt,name=task_priority,json=taskPriority,proto3" json:"task_priority,omitempty"`
	TaskGroupId              string                 `protobuf:"bytes,8,opt,name=task_group_id,json=taskGroupId,proto3" json:"task_group_id,omitempty"`
	TaskCreatedBy            string                 `protobuf:"bytes,9,opt,name=task_created_by,json=taskCreatedBy,proto3" json:"task_created_by,omitempty"`
	TaskAccomplices          string                 `protobuf:"bytes,10,opt,name=task_accomplices,json=taskAccomplices,proto3" json:"task_accomplices,omitempty"`
	TaskAuditors             string                 `protobuf:"bytes,11,opt,name=task_auditors,json=taskAuditors,proto3" json:"task_auditors,omitempty"`
	TaskParentId             string                 `protobuf:"bytes,12,opt,name=task_parent_id,json=taskParentId,proto3" json:"task_parent_id,omitempty"`
	TaskTimeEstimate         string                 `protobuf:"bytes,13,opt,name=task_time_estimate,json=taskTimeEstimate,proto3" json:"task_time_estimate,omitempty"`
	TaskTimeSpent            string                 `protobuf:"bytes,14,opt,name=task_time_spent,json=taskTimeSpent,proto3" json:"task_time_spent,omitempty"`
	TaskTags                 string                 `protobuf:"bytes,15,opt,name=task_tags,json=taskTags,proto3" json:"task_tags,omitempty"`
	Checklist                []*ChecklistItem       `protobuf:"bytes,16,rep,name=checklist,proto3" json:"checklist,omitempty"`
	Subtasks                 []*SubtaskWire         `protobuf:"bytes,17,rep,name=subtasks,proto3" json:"subtasks,omitempty"`
	DependenciesPredecessors []*SubtaskWire         `protobuf:"bytes,18,rep,name=dependencies_predecessors,json=dependenciesPredecessors,proto3" json:"dependencies_predecessors,omitempty"`
	DependenciesSuccessors   []*SubtaskWire         `protobuf:"bytes,19,rep,name=dependencies_successors,json=dependenciesSuccessors,proto3" json:"dependencies_successors,omitempty"`
	TaskUserFields           []*UserFieldWire       `protobuf:"bytes,20,rep,name=task_user_fields,json=taskUserFields,proto3" json:"task_user_fields,omitempty"`
	TaskAttachments          []*TaskAttachmentWire  `protobuf:"bytes,21,rep,name=task_attachments,json=taskAttachments,proto3" json:"task_attachments,omitempty"`
	Comments                 []*TaskComment         `protobuf:"bytes,22,rep,name=comments,proto3" json:"comments,omitempty"`
	History                  []*ChatMessage         `protobuf:"bytes,23,rep,name=history,proto3" json:"history,omitempty"`
	Prompt                   string                 `protobuf:"bytes,24,opt,name=prompt,proto3" json:"prompt,omitempty"`
	AnalysisMode             string                 `protobuf:"bytes,25,opt,name=analysis_mode,json=analysisMode,proto3" json:"analysis_mode,omitempty"`
	Generation               *Generation            `protobuf:"bytes,26,opt,name=generation,proto3" json:"generation,omitempty"`
	OutputFormat             string                 `protobuf:"bytes,27,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_b24llm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_b24llm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_b24llm_proto_rawDescGZIP(), []int{9}
}

func (x *AnalyzeRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AnalyzeRequest) GetTaskTitle() string {
	if x != nil {
		return x.TaskTitle
	}
	return ""
}

func (x *AnalyzeRequest) GetTaskDescription() string {
	if x != nil {
		return x.TaskDescription
	}
	return ""
}

func (x *AnalyzeRequest) GetTaskStatus() string {
	if x != nil {
		return x.TaskStatus
	}
	return ""
}

func (x *AnalyzeRequest) GetTaskDeadline() string {
	if x != nil {
		return x.TaskDeadline
	}
	return ""
}

func (x *AnalyzeRequest) GetTaskAssignee() string {
	if x != nil {
		return x.TaskAssignee
	}
	return ""
}

func (x *AnalyzeRequest) GetTaskPriority() string {
	if x != nil {
		return x.TaskPriority
	}
	return ""
}

func (x *AnalyzeRequest) GetTaskGroupId() string {
	if x != nil {
		return x.TaskGroupId
	}
	return ""
}

func (x *AnalyzeRequest) GetTaskCreatedBy() string {
	if x != nil {
		return x.TaskCreatedBy
	}
	return ""
}

func (x *AnalyzeRequest) GetTaskAccomplices() string {
	if x != nil {
		return x.TaskAccomplices
	}
	return ""
}

func (x *AnalyzeRequest) GetTaskAuditors() string {
	if x != nil {
		return x.TaskAuditors
	}
	return ""
}

func (x *AnalyzeRequest) GetTaskParentId() string {
	if x != nil {
		return x.TaskParentId
	}
	return ""
}

func (x *AnalyzeRequest) GetTaskTimeEstimate() string {
	if x != nil {
		return x.TaskTimeEstimate
	}
	return ""
}

func (x *AnalyzeRequest) GetTaskTimeSpent() string {
	if x != nil {
		return x.TaskTimeSpent
	}
	return ""
}

func (x *AnalyzeRequest) GetTaskTags() string {
	if x != nil {
		return x.TaskTags
	}
	return ""
}

func (x *AnalyzeRequest) GetChecklist() []*ChecklistItem {
	if x != nil {
		return x.Checklist
	}
	return nil
}

func (x *AnalyzeRequest) GetSubtasks() []*SubtaskWire {
	if x != nil {
		return x.Subtasks
	}
	return nil
}

func (x *AnalyzeRequest) GetDependenciesPredecessors() []*SubtaskWire {
	if x != nil {
		return x.DependenciesPredecessors
	}
	return nil
}

func (x *AnalyzeRequest) GetDependenciesSuccessors() []*SubtaskWire {
	if x != nil {
		return x.DependenciesSuccessors
	}
	return nil
}

func (x *AnalyzeRequest) GetTaskUserFields() []*UserFieldWire {
	if x != nil {
		return x.TaskUserFields
	}
	return nil
}

func (x *AnalyzeRequest) GetTaskAttachments() []*TaskAttachmentWire {
	if x != nil {
		return x.TaskAttachments
	}
	return nil
}

func (x *AnalyzeRequest) GetComments() []*TaskComment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *AnalyzeRequest) GetHistory() []*ChatMessage {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *AnalyzeRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *AnalyzeRequest) GetAnalysisMode() string {
	if x != nil {
		return x.AnalysisMode
	}
	return ""
}

func (x *AnalyzeRequest) GetGeneration() *Generation {
	if x != nil {
		return x.Generation
	}
	return nil
}

func (x *AnalyzeRequest) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

type AnalyzeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeResponse) Reset() {
	*x = AnalyzeResponse{}
	mi := &file_b24llm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResponse) ProtoMessage() {}

func (x *AnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_b24llm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_b24llm_proto_rawDescGZIP(), []int{10}
}

func (x *AnalyzeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AnalyzeStreamChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         string                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeStreamChunk) Reset() {
	*x = AnalyzeStreamChunk{}
	mi := &file_b24llm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeStreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeStreamChunk) ProtoMessage() {}

func (x *AnalyzeStreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_b24llm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeStreamChunk.ProtoReflect.Descriptor instead.
func (*AnalyzeStreamChunk) Descriptor() ([]byte, []int) {
	return file_b24llm_proto_rawDescGZIP(), []int{11}
}

func (x *AnalyzeStreamChunk) GetChunk() string {
	if x != nil {
		return x.Chunk
	}
	return ""
}

func (x *AnalyzeStreamChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *AnalyzeStreamChunk) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SummarizeBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AnalyzeRequest      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Generation    *Generation            `protobuf:"bytes,2,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeBatchRequest) Reset() {
	*x = SummarizeBatchRequest{}
	mi := &file_b24llm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeBatchRequest) ProtoMessage() {}

func (x *SummarizeBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_b24llm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeBatchRequest.ProtoReflect.Descriptor instead.
func (*SummarizeBatchRequest) Descriptor() ([]byte, []int) {
	return file_b24llm_proto_rawDescGZIP(), []int{12}
}

func (x *SummarizeBatchRequest) GetItems() []*AnalyzeRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SummarizeBatchRequest) GetGeneration() *Generation {
	if x != nil {
		return x.Generation
	}
	return nil
}

type SummarizeBatchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeBatchResult) Reset() {
	*x = SummarizeBatchResult{}
	mi := &file_b24llm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeBatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeBatchResult) ProtoMessage() {}

func (x *SummarizeBatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_b24llm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeBatchResult.ProtoReflect.Descriptor instead.
func (*SummarizeBatchResult) Descriptor() ([]byte, []int) {
	return file_b24llm_proto_rawDescGZIP(), []int{13}
}

func (x *SummarizeBatchResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SummarizeBatchResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SummarizeBatchResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SummarizeBatchResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Results       []*SummarizeBatchResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeBatchResponse) Reset() {
	*x = SummarizeBatchResponse{}
	mi := &file_b24llm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeBatchResponse) ProtoMessage() {}

func (x *SummarizeBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_b24llm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeBatchResponse.ProtoReflect.Descriptor instead.
func (*SummarizeBatchResponse) Descriptor() ([]byte, []int) {
	return file_b24llm_proto_rawDescGZIP(), []int{14}
}

func (x *SummarizeBatchResponse) GetResults() []*SummarizeBatchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_b24llm_proto protoreflect.FileDescriptor

const file_b24llm_proto_rawDesc = "" +
	"\n" +
	"\fb24llm.proto\x12\x06b24llm\"\x0f\n" +
	"\rHealthRequest\"C\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12!\n" +
	"\ferror_detail\x18\x02 \x01(\tR\verrorDetail\"\x9d\x01\n" +
	"\n" +
	"Generation\x12%\n" +
	"\vtemperature\x18\x01 \x01(\x02H\x00R\vtemperature\x88\x01\x01\x12\"\n" +
	"\n" +
	"max_tokens\x18\x02 \x01(\x05H\x01R\tmaxTokens\x88\x01\x01\x12%\n" +
	"\x0estop_sequences\x18\x03 \x03(\tR\rstopSequencesB\x0e\n" +
	"\f_temperatureB\r\n" +
	"\v_max_tokens\"M\n" +
	"\vTaskComment\x12\x16\n" +
	"\x06author\x18\x01 \x01(\tR\x06author\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x12\n" +
	"\x04time\x18\x03 \x01(\tR\x04time\"9\n" +
	"\rChecklistItem\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04done\x18\x02 \x01(\tR\x04done\"K\n" +
	"\vSubtaskWire\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\";\n" +
	"\rUserFieldWire\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"8\n" +
	"\x12TaskAttachmentWire\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xbc\t\n" +
	"\x0eAnalyzeRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"task_title\x18\x02 \x01(\tR\ttaskTitle\x12)\n" +
	"\x10task_description\x18\x03 \x01(\tR\x0ftaskDescription\x12\x1f\n" +
	"\vtask_status\x18\x04 \x01(\tR\n" +
	"taskStatus\x12#\n" +
	"\rtask_deadline\x18\x05 \x01(\tR\ftaskDeadline\x12#\n" +
	"\rtask_assignee\x18\x06 \x01(\tR\ftaskAssignee\x12#\n" +
	"\rtask_priority\x18\a \x01(\tR\ftaskPriority\x12\"\n" +
	"\rtask_group_id\x18\b \x01(\tR\vtaskGroupId\x12&\n" +
	"\x0ftask_created_by\x18\t \x01(\tR\rtaskCreatedBy\x12)\n" +
	"\x10task_accomplices\x18\n" +
	" \x01(\tR\x0ftaskAccomplices\x12#\n" +
	"\rtask_auditors\x18\v \x01(\tR\ftaskAuditors\x12$\n" +
	"\x0etask_parent_id\x18\f \x01(\tR\ftaskParentId\x12,\n" +
	"\x12task_time_estimate\x18\r \x01(\tR\x10taskTimeEstimate\x12&\n" +
	"\x0ftask_time_spent\x18\x0e \x01(\tR\rtaskTimeSpent\x12\x1b\n" +
	"\ttask_tags\x18\x0f \x01(\tR\btaskTags\x123\n" +
	"\tchecklist\x18\x10 \x03(\v2\x15.b24llm.ChecklistItemR\tchecklist\x12/\n" +
	"\bsubtasks\x18\x11 \x03(\v2\x13.b24llm.SubtaskWireR\bsubtasks\x12P\n" +
	"\x19dependencies_predecessors\x18\x12 \x03(\v2\x13.b24llm.SubtaskWireR\x18dependenciesPredecessors\x12L\n" +
	"\x17dependencies_successors\x18\x13 \x03(\v2\x13.b24llm.SubtaskWireR\x16dependenciesSuccessors\x12?\n" +
	"\x10task_user_fields\x18\x14 \x03(\v2\x15.b24llm.UserFieldWireR\x0etaskUserFields\x12E\n" +
	"\x10task_attachments\x18\x15 \x03(\v2\x1a.b24llm.TaskAttachmentWireR\x0ftaskAttachments\x12/\n" +
	"\bcomments\x18\x16 \x03(\v2\x13.b24llm.TaskCommentR\bcomments\x12-\n" +
	"\ahistory\x18\x17 \x03(\v2\x13.b24llm.ChatMessageR\ahistory\x12\x16\n" +
	"\x06prompt\x18\x18 \x01(\tR\x06prompt\x12#\n" +
	"\ranalysis_mode\x18\x19 \x01(\tR\fanalysisMode\x122\n" +
	"\n" +
	"generation\x18\x1a \x01(\v2\x12.b24llm.GenerationR\n" +
	"generation\x12#\n" +
	"\routput_format\x18\x1b \x01(\tR\foutputFormat\"+\n" +
	"\x0fAnalyzeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"T\n" +
	"\x12AnalyzeStreamChunk\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\tR\x05chunk\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"y\n" +
	"\x15SummarizeBatchRequest\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.b24llm.AnalyzeRequestR\x05items\x122\n" +
	"\n" +
	"generation\x18\x02 \x01(\v2\x12.b24llm.GenerationR\n" +
	"generation\"_\n" +
	"\x14SummarizeBatchResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"P\n" +
	"\x16SummarizeBatchResponse\x126\n" +
	"\aresults\x18\x01 \x03(\v2\x1c.b24llm.SummarizeBatchResultR\aresults2\x95\x02\n" +
	"\x06B24LLM\x127\n" +
	"\x06Health\x12\x15.b24llm.HealthRequest\x1a\x16.b24llm.HealthResponse\x12:\n" +
	"\aAnalyze\x12\x16.b24llm.AnalyzeRequest\x1a\x17.b24llm.AnalyzeResponse\x12E\n" +
	"\rAnalyzeStream\x12\x16.b24llm.AnalyzeRequest\x1a\x1a.b24llm.AnalyzeStreamChunk0\x01\x12O\n" +
	"\x0eSummarizeBatch\x12\x1d.b24llm.SummarizeBatchRequest\x1a\x1e.b24llm.SummarizeBatchResponseBKZIgithub.com/magomedcoder/gen/tools/b24-llm-server/api/pb/b24llmpb;b24llmpbb\x06proto3"

var (
	file_b24llm_proto_rawDescOnce sync.Once
	file_b24llm_proto_rawDescData []byte
)

func file_b24llm_proto_rawDescGZIP() []byte {
	file_b24llm_proto_rawDescOnce.Do(func() {
		file_b24llm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_b24llm_proto_rawDesc), len(file_b24llm_proto_rawDesc)))
	})
	return file_b24llm_proto_rawDescData
}

var file_b24llm_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_b24llm_proto_goTypes = []any{
	(*HealthRequest)(nil),          // 0: b24llm.HealthRequest
	(*HealthResponse)(nil),         // 1: b24llm.HealthResponse
	(*Generation)(nil),             // 2: b24llm.Generation
	(*TaskComment)(nil),            // 3: b24llm.TaskComment
	(*ChecklistItem)(nil),          // 4: b24llm.ChecklistItem
	(*SubtaskWire)(nil),            // 5: b24llm.SubtaskWire
	(*UserFieldWire)(nil),          // 6: b24llm.UserFieldWire
	(*TaskAttachmentWire)(nil),     // 7: b24llm.TaskAttachmentWire
	(*ChatMessage)(nil),            // 8: b24llm.ChatMessage
	(*AnalyzeRequest)(nil),         // 9: b24llm.AnalyzeRequest
	(*AnalyzeResponse)(nil),        // 10: b24llm.AnalyzeResponse
	(*AnalyzeStreamChunk)(nil),     // 11: b24llm.AnalyzeStreamChunk
	(*SummarizeBatchRequest)(nil),  // 12: b24llm.SummarizeBatchRequest
	(*SummarizeBatchResult)(nil),   // 13: b24llm.SummarizeBatchResult
	(*SummarizeBatchResponse)(nil), // 14: b24llm.SummarizeBatchResponse
}
var file_b24llm_proto_depIdxs = []int32{
	4,  // 0: b24llm.AnalyzeRequest.checklist:type_name -> b24llm.ChecklistItem
	5,  // 1: b24llm.AnalyzeRequest.subtasks:type_name -> b24llm.SubtaskWire
	5,  // 2: b24llm.AnalyzeRequest.dependencies_predecessors:type_name -> b24llm.SubtaskWire
	5,  // 3: b24llm.AnalyzeRequest.dependencies_successors:type_name -> b24llm.SubtaskWire
	6,  // 4: b24llm.AnalyzeRequest.task_user_fields:type_name -> b24llm.UserFieldWire
	7,  // 5: b24llm.AnalyzeRequest.task_attachments:type_name -> b24llm.TaskAttachmentWire
	3,  // 6: b24llm.AnalyzeRequest.comments:type_name -> b24llm.TaskComment
	8,  // 7: b24llm.AnalyzeRequest.history:type_name -> b24llm.ChatMessage
	2,  // 8: b24llm.AnalyzeRequest.generation:type_name -> b24llm.Generation
	9,  // 9: b24llm.SummarizeBatchRequest.items:type_name -> b24llm.AnalyzeRequest
	2,  // 10: b24llm.SummarizeBatchRequest.generation:type_name -> b24llm.Generation
	13, // 11: b24llm.SummarizeBatchResponse.results:type_name -> b24llm.SummarizeBatchResult
	0,  // 12: b24llm.B24LLM.Health:input_type -> b24llm.HealthRequest
	9,  // 13: b24llm.B24LLM.Analyze:input_type -> b24llm.AnalyzeRequest
	9,  // 14: b24llm.B24LLM.AnalyzeStream:input_type -> b24llm.AnalyzeRequest
	12, // 15: b24llm.B24LLM.SummarizeBatch:input_type -> b24llm.SummarizeBatchRequest
	1,  // 16: b24llm.B24LLM.Health:output_type -> b24llm.HealthResponse
	10, // 17: b24llm.B24LLM.Analyze:output_type -> b24llm.AnalyzeResponse
	11, // 18: b24llm.B24LLM.AnalyzeStream:output_type -> b24llm.AnalyzeStreamChunk
	14, // 19: b24llm.B24LLM.SummarizeBatch:output_type -> b24llm.SummarizeBatchResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_b24llm_proto_init() }
func file_b24llm_proto_init() {
	if File_b24llm_proto != nil {
		return
	}
	file_b24llm_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_b24llm_proto_rawDesc), len(file_b24llm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_b24llm_proto_goTypes,
		DependencyIndexes: file_b24llm_proto_depIdxs,
		MessageInfos:      file_b24llm_proto_msgTypes,
	}.Build()
	File_b24llm_proto = out.File
	file_b24llm_proto_goTypes = nil
	file_b24llm_proto_depIdxs = nil
}
