// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.30.2
// source: b24llm.proto

package b24llmpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	B24LLM_Health_FullMethodName         = "/b24llm.B24LLM/Health"
	B24LLM_Analyze_FullMethodName        = "/b24llm.B24LLM/Analyze"
	B24LLM_AnalyzeStream_FullMethodName  = "/b24llm.B24LLM/AnalyzeStream"
	B24LLM_SummarizeBatch_FullMethodName = "/b24llm.B24LLM/SummarizeBatch"
)

// B24LLMClient is the client API for B24LLM service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type B24LLMClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	AnalyzeStream(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AnalyzeStreamChunk], error)
	SummarizeBatch(ctx context.Context, in *SummarizeBatchRequest, opts ...grpc.CallOption) (*SummarizeBatchResponse, error)
}

type b24LLMClient struct {
	cc grpc.ClientConnInterface
}

func NewB24LLMClient(cc grpc.ClientConnInterface) B24LLMClient {
	return &b24LLMClient{cc}
}

func (c *b24LLMClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, B24LLM_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *b24LLMClient) Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, B24LLM_Analyze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *b24LLMClient) AnalyzeStream(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AnalyzeStreamChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &B24LLM_ServiceDesc.Streams[0], B24LLM_AnalyzeStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AnalyzeRequest, AnalyzeStreamChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type B24LLM_AnalyzeStreamClient = grpc.ServerStreamingClient[AnalyzeStreamChunk]

func (c *b24LLMClient) SummarizeBatch(ctx context.Context, in *SummarizeBatchRequest, opts ...grpc.CallOption) (*SummarizeBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummarizeBatchResponse)
	err := c.cc.Invoke(ctx, B24LLM_SummarizeBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// B24LLMServer is the server API for B24LLM service.
// All implementations must embed UnimplementedB24LLMServer
// for forward compatibility.
type B24LLMServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	AnalyzeStream(*AnalyzeRequest, grpc.ServerStreamingServer[AnalyzeStreamChunk]) error
	SummarizeBatch(context.Context, *SummarizeBatchRequest) (*SummarizeBatchResponse, error)
	mustEmbedUnimplementedB24LLMServer()
}

// UnimplementedB24LLMServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedB24LLMServer struct{}

func (UnimplementedB24LLMServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedB24LLMServer) Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Analyze not implemented")
}
func (UnimplementedB24LLMServer) AnalyzeStream(*AnalyzeRequest, grpc.ServerStreamingServer[AnalyzeStreamChunk]) error {
	return status.Error(codes.Unimplemented, "method AnalyzeStream not implemented")
}
func (UnimplementedB24LLMServer) SummarizeBatch(context.Context, *SummarizeBatchRequest) (*SummarizeBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SummarizeBatch not implemented")
}
func (UnimplementedB24LLMServer) mustEmbedUnimplementedB24LLMServer() {}
func (UnimplementedB24LLMServer) testEmbeddedByValue()                {}

// UnsafeB24LLMServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to B24LLMServer will
// result in compilation errors.
type UnsafeB24LLMServer interface {
	mustEmbedUnimplementedB24LLMServer()
}

func RegisterB24LLMServer(s grpc.ServiceRegistrar, srv B24LLMServer) {
	// If the following call panics, it indicates UnimplementedB24LLMServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&B24LLM_ServiceDesc, srv)
}

func _B24LLM_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(B24LLMServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: B24LLM_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(B24LLMServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _B24LLM_Analyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(B24LLMServer).Analyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: B24LLM_Analyze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(B24LLMServer).Analyze(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _B24LLM_AnalyzeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AnalyzeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(B24LLMServer).AnalyzeStream(m, &grpc.GenericServerStream[AnalyzeRequest, AnalyzeStreamChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type B24LLM_AnalyzeStreamServer = grpc.ServerStreamingServer[AnalyzeStreamChunk]

func _B24LLM_SummarizeBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummarizeBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(B24LLMServer).SummarizeBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: B24LLM_SummarizeBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(B24LLMServer).SummarizeBatch(ctx, req.(*SummarizeBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// B24LLM_ServiceDesc is the grpc.ServiceDesc for B24LLM service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var B24LLM_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "b24llm.B24LLM",
	HandlerType: (*B24LLMServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _B24LLM_Health_Handler,
		},
		{
			MethodName: "Analyze",
			Handler:    _B24LLM_Analyze_Handler,
		},
		{
			MethodName: "SummarizeBatch",
			Handler:    _B24LLM_SummarizeBatch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AnalyzeStream",
			Handler:       _B24LLM_AnalyzeStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "b24llm.proto",
}
